version: "3"
services:
  dev:
    container_name: dev
    image: joshua7v/dev
    ports:
      - "33000:3000"
      - "37000:7000"
      - "30022:22"
    volumes:
      - /Users/joshua/erinn:/data
    networks:
      - dev

  db:
    container_name: postgres
    image: postgres
    volumes:
      - /Users/joshua/erinn/pgdata/dev:/var/lib/postgresql/data
    networks:
      - dev

networks:
  dev:
