version: "3"
services:
  dev:
    container_name: dev
    image: joshua7v/dev:full
    hostname: dev
    ports:
      - "33000-33010:3000-3010"
      - "34000-34010:4000-4010"
      - "37000:7000"
      - "39000:9000"
      - "30022:22"
    volumes:
      - $HOME/erinn:/data
      - $HOME/Downloads:/hole
    networks:
      - dev

  postgres:
    container_name: postgres
    image: postgres
    hostname: postgres
    volumes:
      - $HOME/erinn/db/postgres/data:/var/lib/postgresql/data
    networks:
      - dev

  mongo:
    container_name: mongo
    image: mongo
    hostname: mongo
    volumes:
      - $HOME/erinn/db/mongo/data:/data/db
    networks:
      - dev

networks:
  dev:
